In [1]:
import pandas as pd

In [2]:
#load cocnepts
concepts=pd.read_csv('/workspaces/master_thesis/CONCEPT.csv', on_bad_lines='skip', sep='\t')

/tmp/ipykernel_2411657/933074145.py:2: DtypeWarning: Columns (6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  concepts=pd.read_csv('/workspaces/master_thesis/CONCEPT.csv', on_bad_lines='skip', sep='\t')

In [3]:
#filter by standard_concept
concepts=concepts[concepts.standard_concept=='S']

In [4]:
concepts

,concept_id,concept_name,domain_id,vocabulary_id,concept_class_id,standard_concept,concept_code,valid_start_date,valid_end_date,invalid_reason
0,1146945,concept.concept_id,Metadata,CDM,Field,S,CDM1,20141111,20991231,NaN
1,1146954,concept.invalid_reason,Metadata,CDM,Field,S,CDM10,20141111,20991231,NaN
2,1147044,observation_period.observation_period_id,Metadata,CDM,Field,S,CDM100,20141111,20991231,NaN
3,756315,metadata.metadata_type_concept_id,Metadata,CDM,Field,S,CDM1000,20210925,20991231,NaN
4,756316,metadata.name,Metadata,CDM,Field,S,CDM1001,20210925,20991231,NaN
...,...,...,...,...,...,...,...,...,...,...
1242677,32761,Person Under Investigation (PUI),Visit,Visit,Visit,S,OMOP4873972,19700101,20991231,NaN
1242678,33004,Supplier / Service Provider,Visit,Visit,Visit,S,OMOP5117446,20210727,20991231,NaN
1242679,33007,Alternate care site (ACS),Visit,Visit,Visit,S,OMOP5117447,20210727,20991231,NaN
1242680,9202,Outpatient Visit,Visit,Visit,Visit,S,OP,19700101,20991231,NaN
1242681,705159,Ambulatory long COVID clinic,Visit,Visit,Visit,S,OMOP5160862,20211215,20991231,NaN

In [5]:
from build_graph import Builder

In [6]:
#build graph
from build_graph import Builder

In [7]:
build = Builder('/workspaces/master_thesis/CONCEPT_RELATIONSHIP.csv', '/workspaces/master_thesis/CONCEPT.csv')

/workspaces/master_thesis/poincare/build_graph.py:11: DtypeWarning: Columns (6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  self.data_concept = pd.read_csv(path_concept, on_bad_lines='skip', sep='\t')

In [8]:
df=build.get_dataframe()

/workspaces/master_thesis/poincare/build_graph.py:41: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data_merge_2=data_merge_2[data_merge_2.standard_concept_x=='S'][data_merge_2.standard_concept_y=='S']

In [9]:
df

,concept_id_1,concept_name_x,concept_id_2,concept_name_y,relationship_id
0,281,Medicare Managed Care,280,Medicare,Is a
1,282,Medicare Health Maintenance Organization (HMO),281,Medicare Managed Care,Is a
2,283,Medicare Preferred Provider Organization (PPO),281,Medicare Managed Care,Is a
3,284,Medicare Point of Service (POS),281,Medicare Managed Care,Is a
4,285,Medicare Non-managed Care,280,Medicare,Is a
...,...,...,...,...,...
1695762,3661632,Thrombocytopenia due to Severe acute respirato...,37311061,COVID-19,Is a
1695763,3655975,Sepsis due to disease caused by Severe acute r...,37311061,COVID-19,Is a
1695764,3661748,Acute kidney injury due to disease caused by S...,37311061,COVID-19,Is a
1695765,3655976,Acute hypoxemic respiratory failure due to dis...,37311061,COVID-19,Is a
1695766,3655977,Rhabdomyolysis due to disease caused by Severe...,37311061,COVID-19,Is a

In [12]:
#get some random records from dataframe
df.sample(10)

,concept_id_1,concept_name_x,concept_id_2,concept_name_y,relationship_id
835696,41995762,Ariano Irpino,41987280,Avellino,Is a
80953,4035539,Electrophoresis method with 8.9 pH buffer,4218575,Electrophoresis measurement,Is a
96001,4047176,Herpes simplex virus identification,4044973,Virus identification,Is a
842995,42003061,Racconigi,41987335,Cuneo,Is a
4907,192669,Gastric fistula,4113547,Lesion of stomach,Is a
1078707,45993375,MC2000 ileostomy bag 5955 55mm Clear (Coloplas...,37209200,NHS dm+d actual appliance,Is a
965339,44798465,Registered general nurse - Royal Army Nursing ...,36685675,Registered nurse - Royal Army Nursing Corps,Is a
187053,4119636,No hip movement,4185176,Joint movement absent,Is a
1101542,46003385,Fulcionel female high waist support briefs wit...,37209200,NHS dm+d actual appliance,Is a
1636355,46279268,Sigvaris Essential Thermoregulating class 2 (2...,37209200,NHS dm+d actual appliance,Is a

In [10]:
#calculate number of nodes and edges 
print('Number of nodes: ', len(df.concept_id_1.unique()))
print('Number of edges: ', len(df))

Number of nodes:  745104
Number of edges:  1111803